version: '2'
services:
  ruby:
    image: ruby:4.0-alpine@sha256:481a20b9e3bfdc5c4d8b86cc1767f987343c06d823888383eda3dc8bc032f0aa
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"