version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:27013907b6320c9a8576c2b4784bce64f84de4ca14f87f9149def1200f2db378
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"