version: '2'
services:
  ruby:
    image: ruby:4.0-alpine@sha256:1ca7cb33e970630d571e0da6140e0bc925faec8f1f8f51f9f2cdf5e5f5eed7c9
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"