name: Junit Annotate
description: Annotates your build using JUnit XML reports
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    artifacts:
      type: string
    job-uuid-file-pattern:
      type: string
    failure-format:
      type: string
      enum:
        - classname
        - file
    fail-build-on-error:
      type: boolean
    context:
      type: string
    report-slowest:
      type: integer
    max-report-size:
      type: integer
  required:
    - artifacts
  additionalProperties: false
