steps:
  - label: ":bash: Plugin"
    plugins:
      docker-compose#v4.9.0:
        run: plugin
  - label: ":ruby: Ruby"
    plugins:
      docker-compose#v4.9.0:
        run: ruby
  - label: "✨ Lint"
    plugins:
      plugin-linter#v3.1.0:
        id: junit-annotate
  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files: hooks/*