steps:
  - label: ":bash: Plugin"
    plugins:
      - plugin-tester#v1.1.1: ~

  - label: ":ruby: Ruby"
    plugins:
      - docker-compose#v5.7.0:
          run: ruby

  - label: "✨ Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: junit-annotate

  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files: hooks/*
