steps:
  - label: ":bash: Plugin"
    plugins:
      docker-compose#v3.5.0:
        run: plugin
  - label: ":ruby: Ruby"
    plugins:
      docker-compose#v3.5.0:
        run: ruby
  - label: "✨ Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: junit-annotate
  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files: hooks/*