steps:
  - label: ":bash: Plugin"
    plugins:
      - plugin-tester#v1.2.0: ~

  - label: ":ruby: Ruby"
    plugins:
      - docker-compose#v5.11.0:
          run: ruby

  - label: "✨ Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: junit-annotate

  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files: hooks/*

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.0:
          variables:
            GITHUB_TOKEN: GITHUB_TOKEN
      - ossf-scorecard#v1.0.1:
          github_token: $$GITHUB_TOKEN
