#!/bin/bash

set -euo pipefail

PLUGIN_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/.."

echo "--- :junit: Download the junits"

artifacts_dir="$(pwd)/$(mktemp -d "junit-annotate-plugin-artifacts-tmp.XXXXXXXXXX")"
annotation_dir="$(pwd)/$(mktemp -d "junit-annotate-plugin-annotation-tmp.XXXXXXXXXX")"
annotation_path="${annotation_dir}/annotation.md"

function cleanup {
  rm -rf "${artifacts_dir}"
  rm -rf "${annotation_dir}"
}

trap cleanup EXIT

buildkite-agent artifact download \
  "${BUILDKITE_PLUGIN_JUNIT_ANNOTATE_ARTIFACTS}" \
  "$artifacts_dir"

echo "--- :junit: Processing the junits"

docker \
  --log-level "error" \
  run \
    --rm \
    --volume "$artifacts_dir:/junits" \
    --volume "$PLUGIN_DIR/ruby:/src" \
    --env "BUILDKITE_PLUGIN_JUNIT_ANNOTATE_JOB_UUID_FILE_PATTERN=${BUILDKITE_PLUGIN_JUNIT_ANNOTATE_JOB_UUID_FILE_PATTERN:-}" \
    ruby:2.5-alpine /src/bin/annotate /junits \
      > "$annotation_path"

cat "$annotation_path"

if grep -q "<details>" "$annotation_path"; then
  echo "--- :buildkite: Creating annotation"
  # shellcheck disable=SC2002
  cat "$annotation_path" | buildkite-agent annotate --context junit --style error
fi